-- LANDING_BANNER (랜딩페이지 배너관리용)
-- 필요할 때 한 번만 실행하세요. (Oracle)

CREATE TABLE LANDING_BANNER (
  BANNER_ID   NUMBER        NOT NULL,
  TITLE       VARCHAR2(100),
  SUB_TITLE   VARCHAR2(200),
  IMAGE_URL   VARCHAR2(300),
  LINK_URL    VARCHAR2(300),
  IS_VISIBLE  CHAR(1)       DEFAULT 'Y',
  SORT_ORDER  NUMBER        DEFAULT 0,
  CREATED_AT  DATE          DEFAULT SYSDATE,
  CONSTRAINT PK_LANDING_BANNER PRIMARY KEY (BANNER_ID)
);

CREATE SEQUENCE SEQ_LANDING_BANNER START WITH 1 INCREMENT BY 1;

-- 샘플 데이터(선택)
INSERT INTO LANDING_BANNER (BANNER_ID, TITLE, SUB_TITLE, IMAGE_URL, LINK_URL, IS_VISIBLE, SORT_ORDER)
VALUES (SEQ_LANDING_BANNER.NEXTVAL, '403 MOTORS', '차량 추천 서비스를 시작해보세요', '/images/logo_2.png', '/main', 'Y', 0);

COMMIT;
